### ISSUE TITLE
Installation problems with rucio Ubuntu 20.0.4

### ISSUE THREAD

**Issue by jfb3615** [cern-fts/gfal2-python#1]
After encountering problems with rucio installation, I traced the problem to gfal2-python, which was not installed.  (I don't know whether it was supposed to be installed automatically with rucio).

So I tried to install it myself using pip3, and that failed during compilation.
Then I tried installing from the git repository and found there the same errors. 

So, 

I hacked two cmake files to fix this inelegantly.  It seems like one problem is that these days, the python version must be appended to a find_package command, so line 19 of CMakeLists.txt 
looks something like this in my inelegant hack:

-find_package(Boost COMPONENTS python REQUIRED)
+find_package(Boost COMPONENTS python38 REQUIRED)

Then in src/CMakeLists.txt, the following inelegant hack was required

include_directories(${Boost_INCLUDE_DIRS}
     ${GLIB2_INCLUDE_DIRS} ${GTHREAD2_INCLUDE_DIRS}
-    ${GFAL2_INCLUDE_DIRS}
+    ${GFAL2_INCLUDE_DIRS} /usr/include/python3.8
 )

I'm sure you don't want to take my "solution" but hopefully with this post you can see that there is a problem to be fixed. 

Best, Joe Boudreau

**Comment by vkuznet** [comment]
I got similar issue with python 3.8 on latest ubuntu. See full build log of `pip install gfal2-python` here: https://github.com/vkuznet/wmcore-builds/runs/7980616854?check_suite_focus=true#step:6:165

In particular here are the failed steps of configure:
```
      -- Configuring incomplete, errors occurred!
      See also "/tmp/pip-install-d65foz6g/gfal2-python_414a2c513b0d495dbd30801ecc90b947/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeOutput.log".
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-d65foz6g/gfal2-python_414a2c513b0d495dbd30801ecc90b947/setup.py", line 87, in <module>
          setup(
        File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
          return orig.install.run(self)
        File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/distutils/command/install.py", line 545, in run
          self.run_command('build')
        File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-d65foz6g/gfal2-python_414a2c513b0d495dbd30801ecc90b947/setup.py", line 84, in run
          _run_make(self.build_temp, self.get_ext_fullpath('gfal2'))
        File "/tmp/pip-install-d65foz6g/gfal2-python_414a2c513b0d495dbd30801ecc90b947/setup.py", line 75, in _run_make
          check_call(cmake_cmd, cwd=build_dir)
        File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '-DSKIP_DOC=TRUE', '-DSKIP_TESTS=TRUE', '-DPYTHON_EXECUTABLE_3=/opt/hostedtoolcache/Python/3.8.13/x64/bin/python', '/tmp/pip-install-d65foz6g/gfal2-python_414a2c513b0d495dbd30801ecc90b947']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> gfal2-python
```
